<?php

/**
 * @file
 * Defines functionality to list the products w.r.t suppliers..
 */

use Drupal\file\Entity\File;
use Drupal\taxonomy\Entity\Term;
use Drupal\user\Entity\User;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_views_view_unformatted().
 */
function product_listing_preprocess_views_view_unformatted(&$variables) {
  if ($variables['view']->id() === 'product_listing_by_supplier') {
    //$punchout_customer_details = _cm_punchout_get_user_details();

    foreach ($variables['view']->result as $id => $row) {

      $product_image_url = '';
      $title = '';
      $packaging_details = '';
      $distributor = '';
      $msrp_price = '';
      $price = '';
      $manufacture_sku = '';
      $variation = '';
    //  dpr(current($row->_relationship_entities[variations]->field_distributor->referencedEntities())->getTitle());
      //dpr($row->_relationship_entities[variations]->field_packaging_details->getValue()[0]['value']);

      if ($row->_relationship_entities[variations]->field_product_images->target_id) {
        $file = File::load($row->_relationship_entities[variations]->field_product_images->target_id);
        $product_image_url = file_url_transform_relative(file_create_url($file->getFileUri()));
      }
      if ($row->_relationship_entities[variations]->title->value) {
        $title = $row->_relationship_entities[variations]->title->value;
      }

      if ($row->_relationship_entities[variations]->field_packaging_details->value) {
        $packaging_details = strip_tags($row->_relationship_entities[variations]->field_packaging_details->value);
      }
      if (current($row->_relationship_entities[variations]->field_distributor->referencedEntities())->getTitle()) {
        $distributor = current($row->_relationship_entities[variations]->field_distributor->referencedEntities())->getTitle();
      }

      if ($row->_relationship_entities[variations]->field_msrp_price->number) {
        $msrp_price = $row->_relationship_entities[variations]->field_msrp_price->number;
      }
      if ($row->_relationship_entities[variations]->price->number) {
        $price = $row->_relationship_entities[variations]->price->number;
      }
      if ($row->_relationship_entities[variations]->field_manufacturer_sku->value) {
        $manufacture_sku = $row->_relationship_entities[variations]->field_manufacturer_sku->value;
      }
      //dpr($row->_entity);
      $variation = $row->_entity->variations->target_id;

      /* $variables['rows'][$id]['content'] = [
        '#theme' => 'product-listing-by-supplier',
        '#product_image_url' => $product_image_url,
        '#title' => $title,
        '#packaging_details' => $packaging_details,
        '#distributor' => $distributor,
        '#msrp_price' => $msrp_price,
        '#price' => $price,
        '#manufacture_sku' => $manufacture_sku,
        '#variation' => $variation,
      ]; */
    }
  }
}

/**
 * Implements hook_theme().
 */
function product_listing_theme() {
  return [
    'product-listing-by-supplier' => [
      'variables' => [
        'product_image_url' => '',
        'title' => '',
        'packaging_details' => '',
        'distributor' => '',
        'msrp_price' => '',
        'price' => '',
        'manufacture_sku' => '',
        'variation' => '',
      ],
    ],
  ];
}
