definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__6':
    weight: 0
    expanded: false
    enabled: true
    menu_name: categories
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.categories.1'
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__7':
    weight: 0
    expanded: false
    enabled: true
    menu_name: categories
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.categories.1'
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__8':
    weight: 0
    expanded: false
    enabled: true
    menu_name: categories
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.categories.1'
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__1':
    weight: 0
    expanded: false
    enabled: true
    menu_name: categories
    parent: ''
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
