<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function cart_icon_popup_theme() {
  return array(
   'cart_icon_popup' => array(
            'variables' => array('title' => NULL, 'link' => NULL, 'items_count' => NULL, 'savings' => NULL),
            'template' => 'header',
        ),
  );
}

/**
* Implements hook_preprocess_HOOK() for block.html.twig.
*/
function curemint_preprocess_block(&$variables){
  if($variables['attributes']['id'] == 'block-customheaderblock') {
    //-- This stops the block being cache in drupal 8
    $variables['#cache']['max-age'] = 0;
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function cart_icon_popup_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  if ($build['#view_mode'] == 'cart' && $entity->getEntityTypeId() == 'commerce_product_variation') {
    $build['product_name']['#markup'] = $entity->getTitle();
  }
}

/**
 * Implements hook_views_pre_render().
 */
function cart_icon_popup_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'commerce_cart_form') {
      // My Codegoes here.
    //$view->header = t('My custom header text');
  }
}