<?php

/**
 * Implements hook_theme().
 */
function cart_icon_popup_theme() {
  return array(
   'cart_icon_popup' => array(
            'variables' => array('title' => NULL, 'link' => NULL, 'items_count' => NULL, 'savings' => NULL),
            'template' => 'header',
        ),
  );
}

/**
* Implements hook_preprocess_HOOK() for block.html.twig.
*/
function curemint_preprocess_block(&$variables){
  if($variables['attributes']['id'] == 'block-customheaderblock') {
    //-- This stops the block being cache in drupal 8
    $variables['#cache']['max-age'] = 0;
  }
}

/**
* Implements hook_theme_suggestions_alter().
*/
/* function curemint_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  $cart_route = \Drupal::routeMatch()->getRouteName();
  if($cart_route == 'commerce_cart.page') {
    $suggestions[] = 'commerce-cart-block-custom.html.twig';
  }
} */
